apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.4.0
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
