apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.4.0
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  values:
    replicaCount: 2

    image:
      repository: docker.io/bitnami/nginx
      tag: 1.27.1-debian-12-r0
      pullPolicy: IfNotPresent

    service:
      type: LoadBalancer
